export const FETCH_TODOS_START = 'FETCH_TODOS_START';
export const FETCH_TODOS_SUCCESS = 'FETCH_TODOS_SUCCESS';
export const FETCH_TODOS_FAILURE = 'FETCH_TODOS_FAILURE';

export const UPDATE_TODOS_START = 'UPDATE_TODOS_START';
export const UPDATE_TODOS_SUCCESS = 'UPDATE_TODOS_SUCCESS';
export const UPDATE_TODOS_FAILURE = 'UPDATE_TODOS_FAILURE';

export const DELETE_TODOS_START = 'DELETE_TODOS_START';
export const DELETE_TODOS_SUCCESS = 'DELETE_TODOS_SUCCESS';
export const DELETE_TODOS_FAILURE = 'DELETE_TODOS_FAILURE';

export const ADD_TODOS_START = 'ADD_TODOS_START';
export const ADD_TODOS_SUCCESS = 'ADD_TODOS_SUCCESS';
export const ADD_TODOS_FAILURE = 'ADD_TODOS_FAILURE';
